### ISSUE TITLE
Setting the -5 to 5 value instead of the temperature

### ISSUE THREAD

**Issue by marcslavec** [Hernas/homebridge-panasonic-heat-pump#11]
**Describe Your Problem:**

First of all, thank you for your effort of implementing the integration. It works really good for me. Since my heating pump is configured with a heating curve, I only change the -5 to +5 scale (currently with the Panasonic comfort app). How would changing the temperature of floor heating interfere with this?

**Comment by bimusiek** [comment]
It wouldn’t. I have same settings in my home and then it will allow you to control between 0-10 degrees. Apple
HomeKit does not support negative temps.

**Comment by marcslavec** [comment]
Ok - so how are you controlling it then at your set up?

Example:
Current heating temp is 28C with setting to 0 offset at the heat pump.
If I set in HomeKit the temperature to 27C - it would then set the offset to -1?

**Comment by bimusiek** [comment]
The homekit temperature will show proper number for current temp, so 28C. But it will show target temp between 0-10. 
So if you have 28c, it will show as 28c and when you try to change it it will show target temp was set to 5. (-5 to 5 shows up as 0-10 so 0 would show up as 5).
