### ISSUE TITLE
Change state of heating and deactivate outdoor temperature

### ISSUE THREAD

**Issue by pawelosin** [Hernas/homebridge-panasonic-heat-pump#3]
Hi, thank You for the great plugin. The plugin is very useful, but I'd like to change two things.
First thing is to change the state of the heating when floor heating and water heating are off. Then tile in the home app is highlighted, but the status still shows information about heating.
![image](https://user-images.githubusercontent.com/39361036/193189102-95f5ad33-492f-4a15-90aa-5eb36157a014.png)
When water heating is active the state of the floor heating shows off and it is correct, at least I think so. 
Second thing is to deactivate outdoor temperature because I don't need it. Is there any way to do it?

**Comment by bimusiek** [comment]
Hey, so the way Homekit shows the state of heating/cooling is by highlighting temp number (orange color for heating, blue for cooling).

Example where both floor & water heating is on, but only one is currently active (so heating the floors now):
![IMG_6253](https://user-images.githubusercontent.com/1025588/195158898-b69e169e-d80a-42f4-ab6c-b0998c4aa7ec.jpg)

I have added new options in 1.3.3:
- Ability to hide comfort mode button
- Ability to hide eco mode button
- Ability to hide outdoor temp sensor

**Comment by bimusiek** [comment]
@pawelosin If this resolves your issue, please close the issue :)
