### ISSUE TITLE
Clarification on licensing

### ISSUE THREAD

**Issue by jichizhang** [Hernas/homebridge-panasonic-heat-pump#5]
According to the README, the project is licensed under MIT.
https://github.com/Hernas/homebridge-panasonic-heat-pump/blob/338ff2ed85f376c67b644262d1e8950beb8554c6/README.md?plain=1#L65

But the attached license file is Apache.
https://github.com/Hernas/homebridge-panasonic-heat-pump/blob/338ff2ed85f376c67b644262d1e8950beb8554c6/LICENSE#L1-L3

Is this dual license intended?

**Comment by bimusiek** [comment]
The LICENSE file was simply forked from electron template, I have to remove it. My code is licensed under MIT.
